package utils

var countryNameCN = map[string]string{
	"afghanistan":                      "阿富汗",
	"albania":                          "阿尔巴尼亚",
	"algeria":                          "阿尔及利亚",
	"andorra":                          "安道尔",
	"angola":                           "安哥拉",
	"antigua and barbuda":              "安提瓜和巴布达",
	"argentina":                        "阿根廷",
	"armenia":                          "亚美尼亚",
	"australia":                        "澳大利亚",
	"austria":                          "奥地利",
	"azerbaijan":                       "阿塞拜疆",
	"bahamas":                          "巴哈马",
	"bahrain":                          "巴林",
	"bangladesh":                       "孟加拉国",
	"barbados":                         "巴巴多斯",
	"belarus":                          "白俄罗斯",
	"belgium":                          "比利时",
	"belize":                           "伯利兹",
	"benin":                            "贝宁",
	"bhutan":                           "不丹",
	"bolivia":                          "玻利维亚",
	"bosnia and herzegovina":           "波斯尼亚和黑塞哥维那",
	"botswana":                         "博茨瓦纳",
	"brazil":                           "巴西",
	"brunei":                           "文莱",
	"bulgaria":                         "保加利亚",
	"burkina faso":                     "布基纳法索",
	"burundi":                          "布隆迪",
	"cambodia":                         "柬埔寨",
	"cameroon":                         "喀麦隆",
	"canada":                           "加拿大",
	"cape verde":                       "佛得角",
	"central african republic":         "中非共和国",
	"chad":                             "乍得",
	"chile":                            "智利",
	"china":                            "中国",
	"colombia":                         "哥伦比亚",
	"comoros":                          "科摩罗",
	"congo":                            "刚果",
	"democratic republic of the congo": "刚果民主共和国",
	"costa rica":                       "哥斯达黎加",
	"croatia":                          "克罗地亚",
	"cuba":                             "古巴",
	"cyprus":                           "塞浦路斯",
	"czech republic":                   "捷克",
	"czechia":                          "捷克",
	"denmark":                          "丹麦",
	"djibouti":                         "吉布提",
	"dominica":                         "多米尼克",
	"dominican republic":               "多米尼加共和国",
	"east timor":                       "东帝汶",
	"timor-leste":                      "东帝汶",
	"ecuador":                          "厄瓜多尔",
	"egypt":                            "埃及",
	"el salvador":                      "萨尔瓦多",
	"equatorial guinea":                "赤道几内亚",
	"eritrea":                          "厄立特里亚",
	"estonia":                          "爱沙尼亚",
	"eswatini":                         "斯威士兰",
	"ethiopia":                         "埃塞俄比亚",
	"fiji":                             "斐济",
	"finland":                          "芬兰",
	"france":                           "法国",
	"gabon":                            "加蓬",
	"gambia":                           "冈比亚",
	"georgia":                          "格鲁吉亚",
	"germany":                          "德国",
	"ghana":                            "加纳",
	"greece":                           "希腊",
	"grenada":                          "格林纳达",
	"guatemala":                        "危地马拉",
	"guinea":                           "几内亚",
	"guinea-bissau":                    "几内亚比绍",
	"guyana":                           "圭亚那",
	"haiti":                            "海地",
	"honduras":                         "洪都拉斯",
	"hong kong":                        "香港",
	"hungary":                          "匈牙利",
	"iceland":                          "冰岛",
	"india":                            "印度",
	"indonesia":                        "印度尼西亚",
	"iran":                             "伊朗",
	"iraq":                             "伊拉克",
	"ireland":                          "爱尔兰",
	"israel":                           "以色列",
	"italy":                            "意大利",
	"ivory coast":                      "科特迪瓦",
	"côte d'ivoire":                    "科特迪瓦",
	"jamaica":                          "牙买加",
	"japan":                            "日本",
	"jordan":                           "约旦",
	"kazakhstan":                       "哈萨克斯坦",
	"kenya":                            "肯尼亚",
	"kiribati":                         "基里巴斯",
	"kosovo":                           "科索沃",
	"kuwait":                           "科威特",
	"kyrgyzstan":                       "吉尔吉斯斯坦",
	"laos":                             "老挝",
	"latvia":                           "拉脱维亚",
	"lebanon":                          "黎巴嫩",
	"lesotho":                          "莱索托",
	"liberia":                          "利比里亚",
	"libya":                            "利比亚",
	"liechtenstein":                    "列支敦士登",
	"lithuania":                        "立陶宛",
	"luxembourg":                       "卢森堡",
	"macau":                            "澳门",
	"macao":                            "澳门",
	"madagascar":                       "马达加斯加",
	"malawi":                           "马拉维",
	"malaysia":                         "马来西亚",
	"maldives":                         "马尔代夫",
	"mali":                             "马里",
	"malta":                            "马耳他",
	"marshall islands":                 "马绍尔群岛",
	"mauritania":                       "毛里塔尼亚",
	"mauritius":                        "毛里求斯",
	"mexico":                           "墨西哥",
	"micronesia":                       "密克罗尼西亚",
	"moldova":                          "摩尔多瓦",
	"monaco":                           "摩纳哥",
	"mongolia":                         "蒙古",
	"montenegro":                       "黑山",
	"morocco":                          "摩洛哥",
	"mozambique":                       "莫桑比克",
	"myanmar":                          "缅甸",
	"burma":                            "缅甸",
	"namibia":                          "纳米比亚",
	"nauru":                            "瑙鲁",
	"nepal":                            "尼泊尔",
	"netherlands":                      "荷兰",
	"new zealand":                      "新西兰",
	"nicaragua":                        "尼加拉瓜",
	"niger":                            "尼日尔",
	"nigeria":                          "尼日利亚",
	"north korea":                      "朝鲜",
	"north macedonia":                  "北马其顿",
	"macedonia":                        "北马其顿",
	"norway":                           "挪威",
	"oman":                             "阿曼",
	"pakistan":                         "巴基斯坦",
	"palau":                            "帕劳",
	"palestine":                        "巴勒斯坦",
	"panama":                           "巴拿马",
	"papua new guinea":                 "巴布亚新几内亚",
	"paraguay":                         "巴拉圭",
	"peru":                             "秘鲁",
	"philippines":                      "菲律宾",
	"poland":                           "波兰",
	"portugal":                         "葡萄牙",
	"qatar":                            "卡塔尔",
	"romania":                          "罗马尼亚",
	"russia":                           "俄罗斯",
	"rwanda":                           "卢旺达",
	"saint kitts and nevis":            "圣基茨和尼维斯",
	"saint lucia":                      "圣卢西亚",
	"saint vincent and the grenadines": "圣文森特和格林纳丁斯",
	"samoa":                            "萨摩亚",
	"san marino":                       "圣马力诺",
	"sao tome and principe":            "圣多美和普林西比",
	"saudi arabia":                     "沙特阿拉伯",
	"senegal":                          "塞内加尔",
	"serbia":                           "塞尔维亚",
	"seychelles":                       "塞舌尔",
	"sierra leone":                     "塞拉利昂",
	"singapore":                        "新加坡",
	"slovakia":                         "斯洛伐克",
	"slovenia":                         "斯洛文尼亚",
	"solomon islands":                  "所罗门群岛",
	"somalia":                          "索马里",
	"south africa":                     "南非",
	"south korea":                      "韩国",
	"korea":                            "韩国",
	"south sudan":                      "南苏丹",
	"spain":                            "西班牙",
	"sri lanka":                        "斯里兰卡",
	"sudan":                            "苏丹",
	"suriname":                         "苏里南",
	"sweden":                           "瑞典",
	"switzerland":                      "瑞士",
	"syria":                            "叙利亚",
	"taiwan":                           "台湾",
	"tajikistan":                       "塔吉克斯坦",
	"tanzania":                         "坦桑尼亚",
	"thailand":                         "泰国",
	"togo":                             "多哥",
	"tonga":                            "汤加",
	"trinidad and tobago":              "特立尼达和多巴哥",
	"tunisia":                          "突尼斯",
	"turkey":                           "土耳其",
	"turkiye":                          "土耳其",
	"türkiye":                          "土耳其",
	"turkmenistan":                     "土库曼斯坦",
	"tuvalu":                           "图瓦卢",
	"uganda":                           "乌干达",
	"ukraine":                          "乌克兰",
	"united arab emirates":             "阿拉伯联合酋长国",
	"united kingdom":                   "英国",
	"uk":                               "英国",
	"united states":                    "美国",
	"united states of america":         "美国",
	"usa":                              "美国",
	"uruguay":                          "乌拉圭",
	"uzbekistan":                       "乌兹别克斯坦",
	"vanuatu":                          "瓦努阿图",
	"vatican city":                     "梵蒂冈",
	"venezuela":                        "委内瑞拉",
	"vietnam":                          "越南",
	"yemen":                            "也门",
	"zambia":                           "赞比亚",
	"zimbabwe":                         "津巴布韦",
}

// countryNameTW 英文国家名（小写） -> 繁体中文
var countryNameTW = map[string]string{
	"afghanistan":                      "阿富汗",
	"albania":                          "阿爾巴尼亞",
	"algeria":                          "阿爾及利亞",
	"andorra":                          "安道爾",
	"angola":                           "安哥拉",
	"antigua and barbuda":              "安地卡及巴布達",
	"argentina":                        "阿根廷",
	"armenia":                          "亞美尼亞",
	"australia":                        "澳大利亞",
	"austria":                          "奧地利",
	"azerbaijan":                       "亞塞拜然",
	"bahamas":                          "巴哈馬",
	"bahrain":                          "巴林",
	"bangladesh":                       "孟加拉",
	"barbados":                         "巴貝多",
	"belarus":                          "白俄羅斯",
	"belgium":                          "比利時",
	"belize":                           "貝里斯",
	"benin":                            "貝南",
	"bhutan":                           "不丹",
	"bolivia":                          "玻利維亞",
	"bosnia and herzegovina":           "波士尼亞與赫塞哥維納",
	"botswana":                         "波札那",
	"brazil":                           "巴西",
	"brunei":                           "汶萊",
	"bulgaria":                         "保加利亞",
	"burkina faso":                     "布吉納法索",
	"burundi":                          "蒲隆地",
	"cambodia":                         "柬埔寨",
	"cameroon":                         "喀麥隆",
	"canada":                           "加拿大",
	"cape verde":                       "維德角",
	"central african republic":         "中非共和國",
	"chad":                             "查德",
	"chile":                            "智利",
	"china":                            "中國",
	"colombia":                         "哥倫比亞",
	"comoros":                          "葛摩",
	"congo":                            "剛果",
	"democratic republic of the congo": "剛果民主共和國",
	"costa rica":                       "哥斯大黎加",
	"croatia":                          "克羅埃西亞",
	"cuba":                             "古巴",
	"cyprus":                           "賽普勒斯",
	"czech republic":                   "捷克",
	"czechia":                          "捷克",
	"denmark":                          "丹麥",
	"djibouti":                         "吉布地",
	"dominica":                         "多米尼克",
	"dominican republic":               "多明尼加共和國",
	"east timor":                       "東帝汶",
	"timor-leste":                      "東帝汶",
	"ecuador":                          "厄瓜多",
	"egypt":                            "埃及",
	"el salvador":                      "薩爾瓦多",
	"equatorial guinea":                "赤道幾內亞",
	"eritrea":                          "厄利垂亞",
	"estonia":                          "愛沙尼亞",
	"eswatini":                         "史瓦帝尼",
	"ethiopia":                         "衣索比亞",
	"fiji":                             "斐濟",
	"finland":                          "芬蘭",
	"france":                           "法國",
	"gabon":                            "加彭",
	"gambia":                           "甘比亞",
	"georgia":                          "喬治亞",
	"germany":                          "德國",
	"ghana":                            "迦納",
	"greece":                           "希臘",
	"grenada":                          "格瑞那達",
	"guatemala":                        "瓜地馬拉",
	"guinea":                           "幾內亞",
	"guinea-bissau":                    "幾內亞比索",
	"guyana":                           "蓋亞那",
	"haiti":                            "海地",
	"honduras":                         "宏都拉斯",
	"hong kong":                        "香港",
	"hungary":                          "匈牙利",
	"iceland":                          "冰島",
	"india":                            "印度",
	"indonesia":                        "印尼",
	"iran":                             "伊朗",
	"iraq":                             "伊拉克",
	"ireland":                          "愛爾蘭",
	"israel":                           "以色列",
	"italy":                            "義大利",
	"ivory coast":                      "象牙海岸",
	"côte d'ivoire":                    "象牙海岸",
	"jamaica":                          "牙買加",
	"japan":                            "日本",
	"jordan":                           "約旦",
	"kazakhstan":                       "哈薩克",
	"kenya":                            "肯亞",
	"kiribati":                         "吉里巴斯",
	"kosovo":                           "科索沃",
	"kuwait":                           "科威特",
	"kyrgyzstan":                       "吉爾吉斯",
	"laos":                             "寮國",
	"latvia":                           "拉脫維亞",
	"lebanon":                          "黎巴嫩",
	"lesotho":                          "賴索托",
	"liberia":                          "賴比瑞亞",
	"libya":                            "利比亞",
	"liechtenstein":                    "列支敦斯登",
	"lithuania":                        "立陶宛",
	"luxembourg":                       "盧森堡",
	"macau":                            "澳門",
	"macao":                            "澳門",
	"madagascar":                       "馬達加斯加",
	"malawi":                           "馬拉威",
	"malaysia":                         "馬來西亞",
	"maldives":                         "馬爾地夫",
	"mali":                             "馬利",
	"malta":                            "馬爾他",
	"marshall islands":                 "馬紹爾群島",
	"mauritania":                       "茅利塔尼亞",
	"mauritius":                        "模里西斯",
	"mexico":                           "墨西哥",
	"micronesia":                       "密克羅尼西亞",
	"moldova":                          "摩爾多瓦",
	"monaco":                           "摩納哥",
	"mongolia":                         "蒙古",
	"montenegro":                       "蒙特內哥羅",
	"morocco":                          "摩洛哥",
	"mozambique":                       "莫三比克",
	"myanmar":                          "緬甸",
	"burma":                            "緬甸",
	"namibia":                          "納米比亞",
	"nauru":                            "諾魯",
	"nepal":                            "尼泊爾",
	"netherlands":                      "荷蘭",
	"new zealand":                      "紐西蘭",
	"nicaragua":                        "尼加拉瓜",
	"niger":                            "尼日",
	"nigeria":                          "奈及利亞",
	"north korea":                      "北韓",
	"north macedonia":                  "北馬其頓",
	"macedonia":                        "北馬其頓",
	"norway":                           "挪威",
	"oman":                             "阿曼",
	"pakistan":                         "巴基斯坦",
	"palau":                            "帛琉",
	"palestine":                        "巴勒斯坦",
	"panama":                           "巴拿馬",
	"papua new guinea":                 "巴布亞紐幾內亞",
	"paraguay":                         "巴拉圭",
	"peru":                             "秘魯",
	"philippines":                      "菲律賓",
	"poland":                           "波蘭",
	"portugal":                         "葡萄牙",
	"qatar":                            "卡達",
	"romania":                          "羅馬尼亞",
	"russia":                           "俄羅斯",
	"rwanda":                           "盧安達",
	"saint kitts and nevis":            "聖克里斯多福及尼維斯",
	"saint lucia":                      "聖露西亞",
	"saint vincent and the grenadines": "聖文森及格瑞那丁",
	"samoa":                            "薩摩亞",
	"san marino":                       "聖馬利諾",
	"sao tome and principe":            "聖多美普林西比",
	"saudi arabia":                     "沙烏地阿拉伯",
	"senegal":                          "塞內加爾",
	"serbia":                           "塞爾維亞",
	"seychelles":                       "塞席爾",
	"sierra leone":                     "獅子山",
	"singapore":                        "新加坡",
	"slovakia":                         "斯洛伐克",
	"slovenia":                         "斯洛維尼亞",
	"solomon islands":                  "索羅門群島",
	"somalia":                          "索馬利亞",
	"south africa":                     "南非",
	"south korea":                      "韓國",
	"korea":                            "韓國",
	"south sudan":                      "南蘇丹",
	"spain":                            "西班牙",
	"sri lanka":                        "斯里蘭卡",
	"sudan":                            "蘇丹",
	"suriname":                         "蘇利南",
	"sweden":                           "瑞典",
	"switzerland":                      "瑞士",
	"syria":                            "敘利亞",
	"taiwan":                           "台灣",
	"tajikistan":                       "塔吉克",
	"tanzania":                         "坦尚尼亞",
	"thailand":                         "泰國",
	"togo":                             "多哥",
	"tonga":                            "東加",
	"trinidad and tobago":              "千里達及托巴哥",
	"tunisia":                          "突尼西亞",
	"turkey":                           "土耳其",
	"turkiye":                          "土耳其",
	"türkiye":                          "土耳其",
	"turkmenistan":                     "土庫曼",
	"tuvalu":                           "吐瓦魯",
	"uganda":                           "烏干達",
	"ukraine":                          "烏克蘭",
	"united arab emirates":             "阿拉伯聯合大公國",
	"united kingdom":                   "英國",
	"uk":                               "英國",
	"united states":                    "美國",
	"united states of america":         "美國",
	"usa":                              "美國",
	"uruguay":                          "烏拉圭",
	"uzbekistan":                       "烏茲別克",
	"vanuatu":                          "萬那杜",
	"vatican city":                     "梵蒂岡",
	"venezuela":                        "委內瑞拉",
	"vietnam":                          "越南",
	"yemen":                            "葉門",
	"zambia":                           "尚比亞",
	"zimbabwe":                         "辛巴威",
}
